# Global variables
DATA_SAVE_DIR = "datasets"
TRAINED_MODEL_DIR = "trained_models"
TENSORBOARD_LOG_DIR = "tensorboard_log"
RESULTS_DIR = "results"

TRAIN_START_DATE = "2010-01-01"
TRAIN_END_DATE = "2020-07-01"
TRADE_START_DATE = "2020-07-01"
TRADE_END_DATE = "2021-10-29"

SLOPE_THRESHOLD_UP = 0.05
SLOPE_THRESHOLD_DOWN = -SLOPE_THRESHOLD_UP